sudo: false

env:
  global:
    - CC_TEST_REPORTER_ID=ce3c363ffb0df9ed6d0d766c56d5f4a03b146a0ca3e348c5a8efc1c496934eed

language: node_js
services: mongodb

branches:
  only:
    - master

node_js:
  - 8
  - 6

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: npm run coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
