sudo: false

language: node_js
services: mongodb

branches:
  only:
    - master

node_js:
  - 8
  - 6

addons:
  code_climate:
    repo_token: 1250a5b6885e3e3c9ee079ea1843777db9e5e9598c5468a0ec91d7eca6f42916

script: npm run coverage

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
